riot.api.key=RGAPI-baf657ed-4796-47f3-86f6-1ac92357ecdd
riot.region.routing=europe
riot.region.platform=euw1
avatars.dir=avatars/
# Discord webhook par défaut (optionnel)
discord.default.webhook=https://discord.com/api/webhooks/1498635854296514620/hZIrUx1oEr8c0EmW4byGK6t9RSGcaKVgygwTDC0IkGGbrDngY3F12Che5lG8gzVZ4hoP